#ifndef GPIO_INTERFACE_H_
#define GPIO_INTERFACE_H_


#define DEFAULT_SPEED  				GPIO_PIN_HIGH_SPEED 
#define DEFAULT_OUTPUT_TYPE  		GPIO_PIN_PUSH_PULL 
#define DEFAULT_INPUT_TYPE  		GPIO_PIN_PULL_UP 

#endif